runtime:
  container_commands:
    - apt-get update && apt-get install -y ffmpeg git gcc libsndfile1
  python:
    version: "3.10"
    requirements:
      - pipeline-ai
      - audiocraft
      - torch==2.0.1
accelerators: null
pipeline_graph: my_musicgen_pipeline: pipeline
pipeline_name: musicgen
