services:
  - type: web
    name: audiocraft-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
